# Generated by Django 4.2.3 on 2023-10-12 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_alter_productvariation_variation_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='product_color',
            field=models.CharField(default='Blue', max_length=100),
        ),
    ]
